#KANISHKA'S CODE
"""
XAI-DocGuard
Explainable AI Module

Generates a human-readable explanation from:

1. Risk Engine
2. Face Matching Module
3. OCR Module
4. Tamper Detection Module

Outputs:
- Summary
- Risk Score
- Risk Level
- Key Factors
- Face Status
- OCR Status
- Tamper Status
- Evidence
- Recommendation
- Visual Heatmap
- Limitation
"""

import cv2
import base64


def generate_explanation(
    tamper_heatmap=None,
    risk_result=None,
    face_result=None,
    ocr_result=None,
    tamper_result=None
):
    """
    Generate a human-readable XAI explanation.

    Parameters
    ----------
    tamper_heatmap : numpy.ndarray, optional
        Heatmap generated by tamper_detection.py.

    risk_result : dict, optional
        Result returned by risk_engine.py.

    face_result : dict, optional
        Result returned by face_match.py.

    ocr_result : dict, optional
        Result returned by ocr_module.py.

    tamper_result : dict, optional
        Result returned by tamper_detection.py.

    Returns
    -------
    dict
        XAI explanation containing risk factors,
        evidence and recommendation.
    """

    # =========================================================
    # 1. SAFELY HANDLE MISSING RESULTS
    # =========================================================

    if not isinstance(risk_result, dict):
        risk_result = {}

    if not isinstance(face_result, dict):
        face_result = {}

    if not isinstance(ocr_result, dict):
        ocr_result = {}

    if not isinstance(tamper_result, dict):
        tamper_result = {}

    # =========================================================
    # 2. RISK ENGINE INFORMATION
    # =========================================================

    risk_score = risk_result.get(
        "risk_score",
        0
    )

    risk_level = risk_result.get(
        "risk_level",
        "UNKNOWN"
    )

    reasons = risk_result.get(
        "reasons",
        []
    )

    risk_contributions = risk_result.get(
        "risk_contributions",
        {}
    )

    recommendation_from_engine = risk_result.get(
        "recommendation"
    )

    # Make sure reasons is a list
    if isinstance(reasons, str):
        reasons = [reasons]

    if not isinstance(reasons, list):
        reasons = []

    # =========================================================
    # 3. FACE MATCHING INFORMATION
    # =========================================================

    matched = face_result.get(
        "matched",
        None
    )

    face_status = face_result.get(
        "status",
        "UNAVAILABLE"
    )

    face_message = face_result.get(
        "message",
        "Face matching result unavailable."
    )

    # ACTUAL REPO FIELD:
    # similarity is already represented as a percentage-like
    # score, so DO NOT multiply it by 100.
    face_similarity = face_result.get(
        "similarity",
        None
    )

    face_risk_score = face_result.get(
        "risk_score",
        None
    )

    face_risk_level = face_result.get(
        "risk_level",
        None
    )

    face_risk_flags = face_result.get(
        "risk_flags",
        []
    )

    if not isinstance(face_risk_flags, list):
        face_risk_flags = [str(face_risk_flags)]

    # =========================================================
    # 4. OCR INFORMATION
    # =========================================================

    ocr_confidence = ocr_result.get(
        "mean_confidence",
        None
    )

    ocr_valid_format = ocr_result.get(
        "is_valid_format",
        None
    )

    ocr_flags = ocr_result.get(
        "flags",
        []
    )

    ocr_token_count = ocr_result.get(
        "token_count",
        None
    )

    structured_fields = ocr_result.get(
        "structured_fields",
        {}
    )

    if not isinstance(ocr_flags, list):
        ocr_flags = [str(ocr_flags)]

    # =========================================================
    # 5. TAMPER INFORMATION
    # =========================================================

    tamper_score = tamper_result.get(
        "tamper_score",
        None
    )

    tamper_reasons = tamper_result.get(
        "reasons",
        []
    )

    if not isinstance(tamper_reasons, list):
        tamper_reasons = [str(tamper_reasons)]

    # If no separate heatmap was supplied,
    # use the heatmap returned by tamper_detection.py.
    if tamper_heatmap is None:

        tamper_heatmap = tamper_result.get(
            "heatmap",
            None
        )

    # =========================================================
    # 6. KEY FACTORS
    # =========================================================

    key_factors = []

    # ---------------------------------------------------------
    # Risk Engine Reasons
    # ---------------------------------------------------------

    for reason in reasons:

        reason = str(reason)

        if reason not in key_factors:

            key_factors.append(
                reason
            )

    # ---------------------------------------------------------
    # Tamper Factors
    # ---------------------------------------------------------

    for reason in tamper_reasons:

        reason = str(reason)

        if reason not in key_factors:

            key_factors.append(
                reason
            )

    # ---------------------------------------------------------
    # Face Factors
    # ---------------------------------------------------------

    if matched is False:

        key_factors.append(
            "Face verification failed."
        )

    elif matched is True:

        key_factors.append(
            "Face matches the document identity."
        )

    if face_similarity is not None:

        try:

            similarity_value = float(
                face_similarity
            )

            key_factors.append(
                f"Face similarity: "
                f"{similarity_value:.1f}%"
            )

        except (
            ValueError,
            TypeError
        ):

            pass

    # ---------------------------------------------------------
    # Face Risk Flags
    # ---------------------------------------------------------

    for flag in face_risk_flags:

        flag_text = str(flag)

        if flag_text not in key_factors:

            key_factors.append(
                f"Face risk flag: {flag_text}"
            )

    # ---------------------------------------------------------
    # OCR Confidence
    # ---------------------------------------------------------

    if ocr_confidence is not None:

        try:

            confidence_value = (
                float(ocr_confidence) * 100
            )

            if confidence_value < 65:

                key_factors.append(
                    f"Low OCR confidence: "
                    f"{confidence_value:.1f}%"
                )

            elif confidence_value < 80:

                key_factors.append(
                    f"Moderate OCR confidence: "
                    f"{confidence_value:.1f}%"
                )

            else:

                key_factors.append(
                    f"High OCR confidence: "
                    f"{confidence_value:.1f}%"
                )

        except (
            ValueError,
            TypeError
        ):

            pass

    # ---------------------------------------------------------
    # OCR Format
    # ---------------------------------------------------------

    if ocr_valid_format is False:

        key_factors.append(
            "OCR document format validation failed."
        )

    elif ocr_valid_format is True:

        key_factors.append(
            "OCR document format validation passed."
        )

    # ---------------------------------------------------------
    # OCR Flags
    # ---------------------------------------------------------

    for flag in ocr_flags:

        flag_text = str(flag)

        factor = (
            f"OCR flag: {flag_text}"
        )

        if factor not in key_factors:

            key_factors.append(
                factor
            )

    # ---------------------------------------------------------
    # Tamper Score
    # ---------------------------------------------------------

    if tamper_score is not None:

        try:

            tamper_value = float(
                tamper_score
            )

            key_factors.append(
                f"Tamper analysis score: "
                f"{tamper_value:.1f}/100"
            )

        except (
            ValueError,
            TypeError
        ):

            pass

    # ---------------------------------------------------------
    # Empty Factors
    # ---------------------------------------------------------

    if not key_factors:

        key_factors.append(
            "No significant contributing factors were provided."
        )

    # =========================================================
    # 7. EVIDENCE
    # =========================================================

    evidence = []

    # ---------------------------------------------------------
    # Tamper Evidence
    # ---------------------------------------------------------

    if tamper_heatmap is not None:

        evidence.append(
            "A tamper-analysis heatmap is available "
            "to visualize suspicious document regions."
        )

    if tamper_score is not None:

        evidence.append(
            "Tamper detection score was included "
            "in the overall risk assessment."
        )

    # ---------------------------------------------------------
    # Face Evidence
    # ---------------------------------------------------------

    if face_similarity is not None:

        evidence.append(
            "Face similarity was considered during "
            "identity verification."
        )

    if face_risk_score is not None:

        evidence.append(
            "The face module's biometric risk score "
            "was considered."
        )

    # ---------------------------------------------------------
    # OCR Evidence
    # ---------------------------------------------------------

    if ocr_confidence is not None:

        evidence.append(
            "OCR confidence was considered when "
            "evaluating extracted document information."
        )

    if ocr_valid_format is not None:

        evidence.append(
            "OCR document-format validation was "
            "considered in the assessment."
        )

    if ocr_token_count is not None:

        evidence.append(
            f"OCR extracted {ocr_token_count} text token(s)."
        )

    # ---------------------------------------------------------
    # Risk Contributions
    # ---------------------------------------------------------

    if risk_contributions:

        evidence.append(
            "Weighted risk contributions were used "
            "to calculate the final risk score."
        )

    # ---------------------------------------------------------
    # No Evidence
    # ---------------------------------------------------------

    if not evidence:

        evidence.append(
            "No additional evidence was provided."
        )

    # =========================================================
    # 8. RECOMMENDATION
    # =========================================================

    level = str(
        risk_level
    ).upper()

    if level == "CRITICAL":

        recommendation = (
            "Document is highly suspicious and "
            "should be escalated for manual investigation."
        )

    elif level == "HIGH":

        recommendation = (
            "Document should be flagged for "
            "detailed manual verification."
        )

    elif level == "MEDIUM":

        recommendation = (
            "Additional manual verification "
            "is recommended."
        )

    elif level == "LOW":

        recommendation = (
            "No major risk indicators detected. "
            "Proceed with normal verification."
        )

    else:

        recommendation = (
            "Human verification is recommended "
            "before making a final decision."
        )

    # If the Risk Engine already generated a
    # recommendation, use that as the primary one.
    if recommendation_from_engine:

        recommendation = (
            recommendation_from_engine
        )

    # =========================================================
    # 9. CONVERT HEATMAP TO BASE64
    # =========================================================

    heatmap_base64 = None

    if tamper_heatmap is not None:

        try:

            # -------------------------------------------------
            # Validate image
            # -------------------------------------------------

            if not hasattr(
                tamper_heatmap,
                "shape"
            ):

                raise TypeError(
                    "Tamper heatmap is not a valid "
                    "OpenCV/numpy image."
                )

            # -------------------------------------------------
            # Resize large images
            # -------------------------------------------------

            height, width = (
                tamper_heatmap.shape[:2]
            )

            if width > 600:

                scale = (
                    600 / width
                )

                new_width = 600

                new_height = int(
                    height * scale
                )

                tamper_heatmap = cv2.resize(
                    tamper_heatmap,
                    (
                        new_width,
                        new_height
                    )
                )

            # -------------------------------------------------
            # Encode as JPEG
            # -------------------------------------------------

            success, buffer = cv2.imencode(
                ".jpg",
                tamper_heatmap
            )

            if success:

                heatmap_base64 = (
                    base64.b64encode(
                        buffer
                    ).decode("utf-8")
                )

        except Exception as error:

            heatmap_base64 = None

            evidence.append(
                "Tamper heatmap could not be encoded "
                "for frontend display."
            )

    # =========================================================
    # 10. FACE STATUS
    # =========================================================

    face_information = {

        "matched":
            matched,

        "status":
            face_status,

        "message":
            face_message,

        "similarity":
            face_similarity,

        "risk_score":
            face_risk_score,

        "risk_level":
            face_risk_level,

        "risk_flags":
            face_risk_flags
    }

    # =========================================================
    # 11. OCR STATUS
    # =========================================================

    ocr_information = {

        "mean_confidence":
            ocr_confidence,

        "is_valid_format":
            ocr_valid_format,

        "token_count":
            ocr_token_count,

        "flags":
            ocr_flags,

        "structured_fields":
            structured_fields
    }

    # =========================================================
    # 12. TAMPER STATUS
    # =========================================================

    tamper_information = {

        "tamper_score":
            tamper_score,

        "reasons":
            tamper_reasons,

        "heatmap_available":
            tamper_heatmap is not None
    }

    # =========================================================
    # 13. FINAL XAI OUTPUT
    # =========================================================

    explanation = {

        # Overall decision
        "summary":
            risk_level,

        "risk_score":
            risk_score,

        "risk_level":
            risk_level,

        # Explainability
        "key_factors":
            key_factors,

        "risk_contributions":
            risk_contributions,

        # Module-specific information
        "face_status":
            face_information,

        "ocr_status":
            ocr_information,

        "tamper_status":
            tamper_information,

        # Evidence
        "evidence":
            evidence,

        # Action
        "recommendation":
            recommendation,

        # Frontend visualization
        "visual_heatmap_base64":
            heatmap_base64,

        # Safety / limitation
        "limitation": (
            "This is an AI-assisted document assessment. "
            "The result does not by itself establish that "
            "a document or identity is fraudulent. "
            "Human verification is required for final decisions."
        )
    }

    return explanation